/* Build step (runs on a dev machine, NOT in the browser): embed every exemplar with MiniLM
   and write vectors.mjs. The browser only ships these vectors + the matcher — never this script. */
import { pipeline } from '@xenova/transformers';
import { writeFileSync } from 'fs';
import { EXEMPLARS } from './exemplars.mjs';

const extractor = await pipeline('feature-extraction', 'Xenova/all-MiniLM-L6-v2');
const vecs = [];
for (const e of EXEMPLARS) {
  const out = await extractor(e.t, { pooling: 'mean', normalize: true });
  vecs.push(Array.from(out.data).map((x) => +x.toFixed(5)));
}
writeFileSync(
  new URL('./vectors.mjs', import.meta.url),
  '/* GENERATED by build-vectors.mjs — do not edit. ' + vecs.length + ' exemplars x ' + vecs[0].length + ' dims. */\n' +
  'export const VECS = ' + JSON.stringify(vecs) + ';\n'
);
console.log('wrote vectors.mjs:', vecs.length, 'exemplars x', vecs[0].length, 'dims');
