/* The "knowledge base": curated vibe phrases -> Fluid params. The matcher embeds the user's
   prompt and returns the nearest exemplar's params. Keys (defaults applied on the Fluid side):
   f=field 0..12, f2=2nd-layer engine, bl=blend 0..5, mix=layerMix 0..1, pal=palette 0..8,
   warp, speed, sym, screen 0..3, pixel, dots, grain, scale.  This file is the IP — grow it. */
export const EXEMPLARS = [
  { t: 'stormy ocean at dusk, churning waves',        f: 10, pal: 2, warp: 7,   speed: 1.0,  scale: 1.8 },
  { t: 'calm zen garden, gentle slow ripples',        f: 1,  pal: 5, warp: 2.5, speed: 0.55, scale: 2.0 },
  { t: 'neon cyberpunk city grid at night',           f: 8,  pal: 8, warp: 6,   speed: 1.0,  pixel: 8,  scale: 1.5 },
  { t: 'northern lights, shimmering aurora borealis', f: 1,  pal: 0, warp: 4,   speed: 0.7,  scale: 2.2 },
  { t: 'molten lava flowing, volcanic heat',          f: 2,  pal: 4, warp: 5,   speed: 0.6,  scale: 1.4 },
  { t: 'crystal cave, sharp geometric facets',        f: 11, pal: 6, warp: 5,   speed: 0.7,  scale: 1.6 },
  { t: 'a swarm of bees, honeycomb hive',             f: 12, pal: 4, warp: 4,   speed: 0.8,  scale: 1.5 },
  { t: 'kaleidoscope mandala, radial symmetry',       f: 6,  pal: 6, warp: 6,   speed: 0.7,  sym: 6, scale: 1.5 },
  { t: 'rippling pond, concentric water rings',       f: 5,  pal: 2, warp: 5,   speed: 0.8,  scale: 1.7 },
  { t: 'sunflower field, golden spiral seeds',        f: 9,  pal: 1, warp: 5,   speed: 0.7,  scale: 1.6 },
  { t: 'circuit board, electronic maze of paths',     f: 4,  pal: 5, warp: 5,   speed: 0.8,  pixel: 6,  scale: 1.5 },
  { t: 'deep space nebula, cosmic dust far away',     f: 10, pal: 6, warp: 6,   speed: 0.5,  scale: 2.6 },
  { t: 'retro arcade game, chunky pixels',            f: 8,  pal: 1, warp: 5,   speed: 0.9,  pixel: 10, scale: 1.5 },
  { t: 'matrix code rain, green hacker terminal',     f: 7,  pal: 5, warp: 6,   speed: 1.0,  screen: 2, pixel: 10, scale: 1.5 },
  { t: 'woven fabric, knitted interlocking threads',  f: 3,  pal: 3, warp: 4,   speed: 0.7,  scale: 1.7 },
  { t: 'psychedelic swirl, trippy and colourful',     f: 1,  pal: 8, warp: 7,   speed: 1.0,  sym: 6, scale: 1.6 },
  { t: 'frozen arctic tundra, cold blue ice',         f: 2,  pal: 2, warp: 3,   speed: 0.55, scale: 1.8 },
  { t: 'electric lightning storm, crackling energy',  f: 5,  pal: 6, warp: 8,   speed: 1.1,  scale: 1.6 },
  { t: 'soft dreamy clouds drifting slowly',          f: 0,  pal: 0, warp: 3,   speed: 0.6,  scale: 2.0 },
  { t: 'fire and ice colliding, two forces',          f: 2,  f2: 1, bl: 4, mix: 0.5, pal: 4, warp: 5, speed: 0.9, scale: 1.6 },
  { t: 'golden spiral galaxy turning slowly',         f: 9,  pal: 4, warp: 6,   speed: 0.7,  scale: 1.6 },
  { t: 'bubbling cauldron, magic potion',             f: 2,  pal: 6, warp: 6,   speed: 0.7,  scale: 1.4 },
  { t: 'calm lavender dawn, soft purple light',       f: 1,  pal: 6, warp: 2.5, speed: 0.55, scale: 2.0 },
  { t: 'liquid chrome metal, polished mercury',       f: 1,  pal: 7, warp: 4,   speed: 0.7,  scale: 1.7 },
  { t: 'ocean waves rolling at sunset',               f: 1,  pal: 1, warp: 4,   speed: 0.7,  scale: 1.9 },
  { t: 'midnight forest, dark mysterious woods',      f: 0,  pal: 3, warp: 4,   speed: 0.6,  scale: 1.8 },
  { t: 'lava lamp, big slow morphing blobs',          f: 2,  pal: 4, warp: 4,   speed: 0.5,  scale: 2.4 },
  { t: 'snowflake crystal mandala, intricate',        f: 11, pal: 2, warp: 6,   speed: 0.6,  sym: 8, scale: 1.5 },
  { t: 'warm campfire glow, drifting embers',         f: 10, pal: 4, warp: 5,   speed: 0.6,  scale: 1.6 },
  { t: 'minimal geometric lines, clean and quiet',    f: 7,  pal: 7, warp: 4,   speed: 0.7,  scale: 1.8 },
  { t: 'tropical coral reef, vivid underwater',       f: 2,  pal: 5, warp: 6,   speed: 0.8,  scale: 1.6 },
  { t: 'desert sand dunes under the noon sun',        f: 1,  pal: 1, warp: 3,   speed: 0.6,  scale: 2.2 },
  { t: 'stained glass cathedral window',              f: 12, pal: 6, warp: 5,   speed: 0.6,  sym: 6, scale: 1.4 },
  { t: 'swirling smoke and grey mist',                f: 10, pal: 7, warp: 5,   speed: 0.7,  scale: 1.8 },
  { t: 'rainbow plasma energy, vivid and electric',   f: 5,  pal: 8, warp: 7,   speed: 1.0,  scale: 1.6 }
];
